export const images = {
  cancel: require('@/assets/images/cancel.png'),
  cloudSurprised: require('@/assets/images/cloud-surprised.png'),
  documents: require('@/assets/images/documents.png'),
  janetSurprised: require('@/assets/images/janet-surprised.png'),
  forward: require('@/assets/images/forward.png'),
  card: require('@/assets/images/card.png'),
  search: require('@/assets/images/search.png'),
  done: require('@/assets/images/done.png'),
  successArrow: require('@/assets/images/depositSuccess.png'),
  depositPending: require('@/assets/images/depositPending.png'),
  depositSuccess: require('@/assets/images/depositSuccess.png'),
  depositError: require('@/assets/images/depositError.png'),
  pause: require('@/assets/images/pause.png'),
  lock: require('@/assets/images/lock.png'),
  safe: require('@/assets/images/safe.png'),
  rocket: require('@/assets/images/rocket.png'),
  barChart: require('@/assets/images/barChart.png'),
  signalGuide: require('@/assets/images/signal-guide.png'),
  portfolioPlaceholder: require('@/assets/images/portfolio-placeholder.png'),
  signalWidgetBg: require('@/assets/images/signal_widget_bg.png'),
  verificationKey: require('@/assets/images/verification-key.png'),
  idCard: require('@/assets/images/id-card.png'),
  blackKey: require('@/assets/images/verification-key.png'),
  signupImage: require('@/assets/images/sign-up_image.png'),
  welcome: require('@/assets/images/welcome.png'),
  twoFactor: require('@/assets/images/two-factor.png'),
  signOut: require('@/assets/images/sign-out.png'),
  googleAuth: require('@/assets/images/google-auth.png'),
  disconnect: require('@/assets/images/disconnect.png'),
  emailVerification: require('@/assets/images/email-verification.png'),
  questionnaireVerification: require('@/assets/images/questionnaire-verification.png'),
  identityVerification: require('@/assets/images/identity-verification.png'),
  coins: require('@/assets/images/coins.png'),
  cardImageWithWave: require('@/assets/images/cardImageWithWave.png'),
  bonusMoney:require('@/assets/images/bonus-money.png'),
  credit:require('@/assets/images/credit.png'),
  one:require('@/assets/images/one.png'),
  two:require('@/assets/images/two.png'),
  three:require('@/assets/images/three.png'),
  cancelImage:require('@/assets/images/cancel-image.png'),
  userImage:require('@/assets/images/user-photo.png'),
  sliderBg1:require('@/assets/images/slider-bg-1.png'),
  sliderBg2:require('@/assets/images/slider-bg-2.png'),
  sliderBg3:require('@/assets/images/slider-bg-3.png'),
  phoneVerification:require('@/assets/images/phone-verification.png'),
  confirmation: require('@/assets/images/confirmation.png'),
  keyWithBackground:require('@/assets/images/key-with-background.png'),
  carousel1:require('@/assets/images/carousel-1.png'),
  carousel2:require('@/assets/images/carousel-2.png'),
  carousel3:require('@/assets/images/carousel-3.png'),
  verifyBanner:require('@/assets/images/verify-banner.png'),
  verifyUser:require('@/assets/images/verify-user.png'),
  pspFee:require('@/assets/images/psp-fee.png'),
  dormantFee:require('@/assets/images/dormant-fee.png'),
  blurredSignal:require('@/assets/images/blurredSignal.png'),
  introBg: require('@/assets/images/intro-bg.png'),
  foreground1: require('@/assets/images/foreground-1.png'),
  foreground2: require('@/assets/images/foreground-2.png'),
  foreground3: require('@/assets/images/foreground-3.png'),
  referralAvatar: require('@/assets/images/referral-avatar.png'),
  giftBox:require('@/assets/images/giftbox.png'),
  arrowBuy: require('@/assets/images/arrowBuy.png'),
  arrowSell: require('@/assets/images/arrowSell.png'),
  timer: require('@/assets/images/timer.png'),
}
