import { SvgProps } from 'react-native-svg';
import { StyleProp, ViewStyle } from 'react-native';

export enum SvgXmlIconNames {
  deposit = 'deposit',
  withdrawal = 'withdrawal',
  closedAccount = 'closed-account',
  walletAccount = 'wallet-account',
  tradingAccount = 'trading-account',
  rewardsAccount = 'rewards-account',
  cashbackAccount = 'cashback-account',
  logo = 'logo',
  ideasHub = 'ideas-hub',
  portfolio = 'portfolio',
  marketings = 'marketings',
  wallet = 'wallet',
  bankCard = 'bankCard',
  chevronLeft = 'chevron-left',
  chevronRight = 'chevron-right',
  chevronBottom = 'chevron-bottom',
  chevronTop = 'chevron-top',
  lineChartUp = 'line-chart-up',
  check = 'check',
  eye = 'eye',
  eyeSlash = 'eye-slash',
  magnify = 'magnify',
  close = 'close',
  closeCircle = 'close-circle',
  star = 'star',
  person = 'person',
  list = 'list',
  questionCircle = 'question-circle',
  googleColor = 'google-color',
  facebookColor = 'facebook-color',
  arrowAngle = 'arrow-angle',
  arrowLeft = 'arrow-left',
  arrowRight = 'arrow-right',
  arrowUp = 'arrow-up',
  clock = 'clock',
  multiply = 'multiply',
  exclamation = 'exclamation',
  chevronDown = 'chevron-down',
  calendar = 'calendar',
  lineCurve = 'line-curve',
  candleStick = 'candle-stick',
  attach = 'attach',
  signal = 'signal',
  bankNote = 'bankNote',
  file = 'file',
  fileColored = 'file-colored',
  plus = 'plus',
  transfer = 'transfer',
  diamond = 'diamond',
  coinsStack = 'coinsStack',
  grid = 'grid',
  listView = 'listView',
  settings = 'settings',
  lineChart = 'lineChart',
  glasses = 'glasses',
  verificationKey = 'verificationKey',
  rocket = 'rocket',
  coins = 'coins',
  candleStickGreen = 'candleStickGreen',
  closePurple = 'closePurple',
  ideasHubActive = 'ideasHubActive',
  portfolioIconActive = 'portfolioIconActive',
  marketIconActive = 'marketIconActive',
  walletIconActive = 'walletIconActive',
  pencil = 'pencil',
  copy = 'copy',
  paste = 'paste',
  shareIcon='shareIcon',
  cashback = 'cashback',
  checkThin = 'checkThin',
  welcome = 'welcome',
  pause = 'pause',
  halfMoon = 'halfMoon',
  lock = 'lock',
  roundClock = 'roundClock',
  contest = 'contest',
  cupa = 'cupa',
  contestRound = 'contestRound',
  demoContestRound = 'demoContestRound',
  rewards = 'rewards',
  balanceCorrection = 'balanceCorrection',
  fileCopy = 'fileCopy',
  userSquare = 'userSquare',
  checkVerified = 'checkVerified',
  diamondUnderline = 'diamondUnderline',
  lockPlain = 'lockPlain',
  gift = 'gift',
  money = 'money',
  people = 'people',
  rewardsWalletCashbackIcon = 'rewardsWalletCashbackIcon',
  rewardsWalletPeopleIcon = 'rewardsWalletPeopleIcon',
  rewardsWalletGiftIcon = 'rewardsWalletGiftIcon',
  mainWallet = 'mainWallet',
  bonusWallet = 'bonusWallet',
  primeWallet = 'primeWallet',
  referral = 'referral',
  transactionsHistory = 'transactionsHistory',
  user='user',
  pulse='pulse',
  recentTrades='recentTrades',
  topPerformers='topPerformers',
  topSignals='topSignals',
  triangle='triangle',
  smallClock='smallClock',
  arrowInCircle='arrowInCircle',
  smallArrowUp='smallArrowUp',
  smallArrowDown='smallArrowDown',
  pulseAIIcon='pulseAIIcon',
  recentTradesSoon='recentTradesSoon',
  pulseActive='pulseActive'
}

export interface SvgXmlProps extends SvgProps {
  name: SvgXmlIconNames;
  size?: {
    width: number;
    height: number;
  };
  width?: number;
  height?: number;
  color?: string;
  style?: StyleProp<ViewStyle>;
}
