source 'https://cdn.cocoapods.org/'
source 'https://github.com/SumSubstance/Specs.git'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.6'
prepare_react_native_project!

# install! 'cocoapods', :deterministic_uuids => false

ENV['RCT_NEW_ARCH_ENABLED'] = '1'

# Enable MRTDReader (NFC) module
ENV['IDENSIC_WITH_MRTDREADER'] = 'true'

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'amegaCapital' do
  # Use React Native Native Modules
  config = use_native_modules!

  use_frameworks! :linkage => :static

  # Use React Native
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => true,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Additional Pods
  pod 'react-native-branch', path: '../node_modules/react-native-branch'
  pod 'react-native-config', path: '../node_modules/react-native-config'

  if ENV['IDENSIC_WITH_MRTDREADER']
    pod 'OpenSSL-Universal', :configurations => ['Debug', 'Release']
  end

  # Schemes
  target 'amegaCapitalDev' do
    inherit! :complete
  end

  target 'amegaCapitalQA' do
    inherit! :complete
  end

  target 'amegaCapitalStage' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(
      installer, 
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.6'
      end
    end
  end
end
